<a href="https://colab.research.google.com/github/shivang1234gupta/CelebrityProfiling/blob/master/CelebrityMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


**Preprocessing the data**

In [3]:
import pandas as pd
df=pd.read_csv('drive/My Drive/Random/Dataset.csv')
y=pd.read_csv('drive/My Drive/Random/Output.csv')

In [4]:
!pip install git+https://github.com/laxmimerit/preprocess_kgptalkie.git
import preprocess_kgptalkie as ps

  Cloning https://github.com/laxmimerit/preprocess_kgptalkie.git to /tmp/pip-req-build-g779fthj
  Running command git clone -q https://github.com/laxmimerit/preprocess_kgptalkie.git /tmp/pip-req-build-g779fthj
  Created wheel for preprocess-kgptalkie: filename=preprocess_kgptalkie-0.0.5-cp36-none-any.whl size=4517 sha256=b50171fe455ff48d8e95cc319117080dc45cfe29d3939b9b5f47e6f653c494ae
  Stored in directory: /tmp/pip-ephem-wheel-cache-t0sy4gu9/wheels/a8/18/22/90afa4bd43247fb9a75b710a4a3fcd94966c022ce9e3c7d0a6
Successfully built preprocess-kgptalkie


In [5]:
df['tweet'] = df['tweet'].apply(lambda x: str(x).lower())
df['tweet'] = df['tweet'].apply(lambda x: ps.cont_exp(x))

df['tweet'] = df['tweet'].apply(lambda x: ps.remove_special_chars(x))
df['tweet'] = df['tweet'].apply(lambda x: ps.remove_accented_chars(x))

In [6]:
df['tweet'] = df['tweet'].apply(lambda x: ps.remove_html_tags(x))


In [7]:
df['tweet'] = df['tweet'].apply(lambda x: ps.remove_urls(x))

In [8]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
df['tweet'] = df['tweet'].apply(lambda x: ps.spelling_correction(x))

In [12]:
df['tweet'][1]

'not too much drama but its still drama kickin off tutorialtuesday with my chillowt look excited to show ya some of my own tips for the new fentybeauty holiday collection out now peep the full vid at httpstco8lxyfjz7pf httpstcosasdfqnqo2 join tidal and my rocnation fam in their efforts to reform criminal justice with their annual tidalxbrooklyn benefit concert on 1023 get your tix learn more about the cause and donate at httpstco4ure4l722w httpstcoue4ets1bvx chillowt is out now i created this icy hot holiday collection to make sure you look all winter long i love using the killawattfoilpalette on my eyes cheeks its versatile af get it at fentybeauty sephora harveynichols and sephorainjcp httpstcoqw885ko2vs httpstcodm4jmvzp5x good morning americai dont care what responsibilities you have today theres no greater responsibility than being in control of your future and it starts now register to vote today at httpstcok42tb6cviz triple check that you are properly registered lets go httpstcoi

Using GloVe pretrained word embeddings

In [13]:
glove_vectors = dict()

In [14]:
import numpy as np


In [15]:
%%time

file = open('/content/drive/My Drive/glove.6B.100d.txt', encoding='utf-8')

for line in file:
    values = line.split()
    
    word  = values[0]
    vectors = np.asarray(values[1:])
    glove_vectors[word] = vectors
    
file.close()

CPU times: user 14 s, sys: 629 ms, total: 14.7 s
Wall time: 16 s


In [ ]:
glove_vectors

In [16]:
len(glove_vectors)

400000

In [17]:
vec_shape=100

In [18]:
def get_vec(x):
    arr = np.zeros(vec_shape)
    text = str(x).split()
    
    for t in text:
        try:
            vec = glove_vectors.get(t).astype(float)
            arr = arr + vec
        except:
            pass
        
    arr = arr.reshape(1, -1)[0]
    return arr/len(text)

Finally word embedded to vectors

In [ ]:
%%time
df['vec'] = df['tweet'].apply(lambda x: get_vec(x))

CPU times: user 31min 22s, sys: 1.61 s, total: 31min 23s
Wall time: 31min 25s


In [ ]:
df['vec']
df.fillna(value=0)
df['vec'].isnull().sum()

In [20]:
from sklearn.externals import joblib

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
joblib.dump(df['vec'], 'drive/My Drive/Random/preprocess.pkl') 

['drive/My Drive/Random/preprocess.pkl']

Gender Classification of celebrity

In [57]:
X=joblib.load('drive/My Drive/Random/preprocess.pkl') 

In [58]:
vec_shape=100
X = np.concatenate(X, axis = 0).reshape(-1, vec_shape)

In [59]:
type(X)

numpy.ndarray

In [60]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y['gen'] = le.fit_transform(y['gen'])

In [61]:
import numpy as np
X_final=X
y_final=y['gen'].to_numpy()

In [62]:
np.all(np.isfinite(X_final))

False

In [63]:
np.any(np.isnan(X_final))

True

In [64]:
X_final.shape
#np.any(np.isnan(X_final))

(14499, 100)

In [65]:
X_final[0].shape

(100,)

In [66]:
from numpy import *
where_are_NaNs = isnan(X_final)
X_final[where_are_NaNs] = 0

In [72]:
X_final[X_final == inf] = 0

In [73]:
np.any(np.isnan(X_final))

False

In [74]:
np.all(np.isfinite(X_final))

True

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,random_state=40,test_size=.2)

In [76]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report, confusion_matrix
clf = LogisticRegression(solver = 'liblinear', multi_class='auto')


In [77]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [78]:
y_pred = clf.predict(X_test)

In [79]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.52      0.63       804
           1       0.84      0.95      0.89      2093
           2       0.00      0.00      0.00         3

    accuracy                           0.83      2900
   macro avg       0.54      0.49      0.51      2900
weighted avg       0.82      0.83      0.82      2900



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [80]:
print(confusion_matrix(y_test, y_pred))

[[ 415  389    0]
 [ 103 1990    0]
 [   2    1    0]]


In [81]:
from sklearn.svm import LinearSVC

In [82]:
clf = LinearSVC()
clf.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [83]:
y_pred = clf.predict(X_test)

In [84]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.62      0.70       804
           1       0.87      0.94      0.90      2093
           2       0.00      0.00      0.00         3

    accuracy                           0.85      2900
   macro avg       0.55      0.52      0.53      2900
weighted avg       0.84      0.85      0.84      2900



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Fame Classification

In [85]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y['fame'] = le.fit_transform(y['fame'])

In [88]:
import numpy as np
X_final=X
y_final=y['fame'].to_numpy()

In [89]:
X_final.shape

(14499, 100)

In [90]:
from numpy import *
where_are_NaNs = isnan(X_final)
X_final[where_are_NaNs] = 0

In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,random_state=40,test_size=.2)

In [92]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report, confusion_matrix
clf = LogisticRegression(solver = 'liblinear', multi_class='auto')


In [94]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [95]:
y_pred = clf.predict(X_test)

In [96]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       139
           1       0.76      0.99      0.86      2175
           2       0.55      0.06      0.10       586

    accuracy                           0.75      2900
   macro avg       0.44      0.35      0.32      2900
weighted avg       0.68      0.75      0.66      2900



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [97]:
print(confusion_matrix(y_test, y_pred))

[[   0  139    0]
 [   0 2148   27]
 [   0  553   33]]


In [98]:
from sklearn.svm import LinearSVC

In [104]:
from sklearn.svm import SVC

In [99]:
clf = LinearSVC()
clf.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [100]:
y_pred = clf.predict(X_test)

In [101]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       139
           1       0.76      0.99      0.86      2175
           2       0.51      0.06      0.10       586

    accuracy                           0.75      2900
   macro avg       0.42      0.35      0.32      2900
weighted avg       0.67      0.75      0.66      2900



In [102]:
print(confusion_matrix(y_test, y_pred))

[[   0  138    1]
 [   1 2143   31]
 [   0  553   33]]


In [106]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [107]:
y_pred = clf.predict(X_test)

In [108]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       139
           1       0.76      0.99      0.86      2175
           2       0.51      0.06      0.10       586

    accuracy                           0.75      2900
   macro avg       0.42      0.35      0.32      2900
weighted avg       0.67      0.75      0.66      2900



Occupation classification

In [109]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y['occ'] = le.fit_transform(y['occ'])

In [113]:
import numpy as np
X_final=X
y_final=y['occ'].to_numpy()

In [114]:
from numpy import *
where_are_NaNs = isnan(X_final)
X_final[where_are_NaNs] = 0

In [115]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,random_state=40,test_size=.2)

In [116]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report, confusion_matrix
clf = LogisticRegression(solver = 'liblinear', multi_class='auto')


In [117]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [118]:
y_pred = clf.predict(X_test)

In [119]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.36      0.42       469
           1       0.00      0.00      0.00        75
           2       0.65      0.84      0.73       818
           3       0.67      0.73      0.70       234
           4       0.00      0.00      0.00        52
           5       0.00      0.00      0.00         2
           6       0.50      0.01      0.03        67
           7       0.84      0.89      0.86      1183

    accuracy                           0.71      2900
   macro avg       0.39      0.35      0.34      2900
weighted avg       0.67      0.71      0.68      2900



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [120]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [121]:
y_pred = clf.predict(X_test)

In [122]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.36      0.42       469
           1       0.00      0.00      0.00        75
           2       0.65      0.84      0.73       818
           3       0.67      0.73      0.70       234
           4       0.00      0.00      0.00        52
           5       0.00      0.00      0.00         2
           6       0.50      0.01      0.03        67
           7       0.84      0.89      0.86      1183

    accuracy                           0.71      2900
   macro avg       0.39      0.35      0.34      2900
weighted avg       0.67      0.71      0.68      2900



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [123]:
classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [124]:
y_pred = clf.predict(X_test)

In [125]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.36      0.42       469
           1       0.00      0.00      0.00        75
           2       0.65      0.84      0.73       818
           3       0.67      0.73      0.70       234
           4       0.00      0.00      0.00        52
           5       0.00      0.00      0.00         2
           6       0.50      0.01      0.03        67
           7       0.84      0.89      0.86      1183

    accuracy                           0.71      2900
   macro avg       0.39      0.35      0.34      2900
weighted avg       0.67      0.71      0.68      2900



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
